owncloud/docs-main

.drone.star
modules/ROOT/pages/client_releases.adoc
modules/ROOT/pages/how_to_contribute.adoc
modules/ROOT/pages/index.adoc
modules/ROOT/pages/ocis_release_notes.adoc
modules/ROOT/pages/ocis_releases.adoc
modules/ROOT/pages/server_release_notes.adoc
modules/ROOT/pages/server_releases.adoc

Finalizes #1 and https://github.com/owncloud/docs/pull/4921 which now adds CI (.drone.star) and redirects to all pages so they are available on the old link.
After merging this, I will update the branch protection rules to include CI and approvals.
@EParzefall @phil-davis fyi

Fix CI and add redirects

---

antora.yml

This PR prepares to make the landing page of the site commponent and version less:
`doc.owncloud.com` will not longer redirect to `doc.owncloud.com/docs_main/next`
This is a great improvement as robots.txt and site.yml will now work correctly in Google indexing.
Needs also a change in the docs repo which will come as second step.

Make the landing page component and versionless

---

modules/ROOT/pages/client_releases.adoc
modules/ROOT/pages/how_to_contribute.adoc
modules/ROOT/pages/index.adoc
modules/ROOT/pages/ocis_release_notes.adoc
modules/ROOT/pages/ocis_releases.adoc
modules/ROOT/pages/server_release_notes.adoc
modules/ROOT/pages/server_releases.adoc

References: #23 
Add a page alias to all pages so that the former `docs_main/next` will still get resolved and redirected to the component less version. This eases life as some may not want to flush the browser cache. It is only 7 pages...

Make a page-aliases for all pages

---

modules/ROOT/pages/desktop_release_notes.adoc
modules/ROOT/partials/nav.adoc

This adds a release notes page for the Desktop App as that one was removed from the Desktop App manual with a separate PR, see https://github.com/owncloud/docs-client-desktop/pull/588
I added release notes down to 5.0 to have some content. The latest release notes are a polished version of the formerly existing release notes that are removed via the referenced PR.
We now can much more easily add release notes as we are used to like with Server and Infinite Scale.
Note, I will do the same thing for iOS and Android for completeness.
@tbsbdr fyi

Add Desktop App release notes

---

modules/ROOT/pages/android_release_notes.adoc
modules/ROOT/pages/desktop_release_notes.adoc
modules/ROOT/pages/ios_release_notes.adoc
modules/ROOT/partials/nav.adoc

Adding the iOS and Android release notes to have all apps completed.
The release notes page in the apps will be removed as it contains nothing valuable.
@tbsbdr fyi

Adding iOS and Android release notes

---

modules/ROOT/pages/ocis_release_notes.adoc
modules/ROOT/pages/ocis_releases.adoc

This are the ocis 5.0.0 release notes which originally were filed in https://github.com/owncloud/docs/pull/4911
Due to splitting into the repos **docs** (full site build only) and **docs-main** (main page content), the referenced PR moved here. All content at the time of moving is identical !
Note, do not merge atm, the migration is not finished and I need to setup branchprotection rules for this repo.

ocis 5.0.0 release notes

---

modules/ROOT/pages/desktop_release_notes.adoc

This PR adds a temporary page alias for the desktop release notes so they can be accessible via: [desktop/5.2/appendices/release_notes.html](https://doc.owncloud.com/desktop/5.2/appendices/release_notes.html)
Locally tested via a full docs build ✔️ 
@tbsbdr fyi, as discussed

Add a temporary page alias for the desktop release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

This rephrases the deprecation of the resharing feature.
**Additional actions need to be taken:**
* Updating the migration guide to reflect settting the envvar to false
See: https://github.com/owncloud/docs-ocis/pull/747
* Urgently adding a PR in the ocis repo to deprecate the `xxx_RESHARING_ENABLED` envvars
See: https://github.com/owncloud/ocis/pull/8659

Rephrasing the deprecation of the resharing feature

---

modules/ROOT/pages/ocis_release_notes.adoc
site.yml

Refernces: https://github.com/owncloud/ocis/pull/8825 ([full-ci] Prepare Release 5.0.1)
Adds release notes for ocis 5.0.1 based on the changes in the referenced PR.
Note that the changes in site.yml are just for local building and have no impact on a full build but they should be "as close as possible" 😄 
Should be merged close after the new version is publicly available.

Add release notes for ocis 5.0.1

---

modules/ROOT/pages/ocis_release_notes.adoc

Add ocis 5.0.2 release notes.
Release changes in docs and docs-ocis are on the way.

Add ocis 5.0.2 release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

This are the release notes for Infinite Scale 5.0.3
There will be two more PR, one in docs and one in docs-ocis to point to the 5.0.3 release.

Release notes for ocis 5.0.3

---

modules/ROOT/pages/ocis_release_notes.adoc
site.yml

Infinite scale 5.0.4 has been released - this are the release notes.

Add release notes for ocis 5.0.4

---

modules/ROOT/pages/desktop_release_notes.adoc

References: https://github.com/owncloud/docs/pull/4964 (Changes necessary for Desktop 5.3)
This PR adds Desktop v5.3.0 release notes.
Note that the RN are taken from `v5.3.0-rc.1` as no other info currently exists.
Should be merged after merging docs/pull/4964
@TheOneRing

Add Desktop v5.3.0 release notes

---

modules/ROOT/pages/server_release_notes.adoc

Referencing: https://github.com/owncloud/docs/pull/4965 (Changes necessary to show server 10.15)
* Fixed rendering to be inline with the ocis release notes
Note, no text changes made, only adding `[descrete]` to a section heading to avoid rendering and fixed casing in the section name where necessary. The TOC is now created fully automated by Antora.
* Added a COMMENTED section for 10.15 which can be used as starting point for an upcoming release notes PR.

Fix server release notes to prepare for changes necessary for 10.15

---

modules/ROOT/pages/android_release_notes.adoc

Adding release notes for Android 4.3.0
Note, there was a thread [adding important stuff as text description](https://github.com/owncloud/android/issues/4359#issuecomment-2189401417).
We could add that easily here or need to file another PR post merging.
We could also remove not that relevant stuff like:
* Add new prefixes in commit messages of 3rd party contributors:
https://github.com/owncloud/android/issues/4346[#4346]
* Kotlinize PreviewTextFragment:
https://github.com/owncloud/android/issues/4356[#4356]
* Unit tests for repository classes - Part 1:
https://github.com/owncloud/android/issues/4232[#4232]
* ...

Adding release notes for Android 4.3.0

---

modules/ROOT/pages/ocis_release_notes.adoc

This PR supersedes #50 (Add release notes ocis 6.0.0 (rolling))
This is because there was an issue with rebasing, ocis 5.0.5 has been merged in the meanwhile. A local build is now working again - sorry for the inconvinience.
The PR consists of currently two commits. The first one is identical to #50 + a working rebase, the second one contains fixes and updates I added.
A local build now runs fine and the rendered output is now correct.
@micbar there are two locations where you are text wise mentioned and your input is needed - else this cant be merged.

NEW: add release notes ocis 6.0.0 (rolling)

---

modules/ROOT/pages/ocis_release_notes.adoc

Release notes for the rolling release.
Version number needs to be adjusted/checked. (Currently assuming 6.1.0)

Release Notes for ocis rolling 8th Jul 2024

---

modules/ROOT/pages/ocis_release_notes.adoc

This is the starting point for the 5.0.6 docs to make adding content more easy.
Note that the commented line is by intention to have a first structure. Uncomment and change stuff as needed...

Prepare for ocis 5.0.6 release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

As the title says, derived from https://github.com/owncloud/ocis/issues/9962 (Patch Release 5.0.7)
Merge only after the release has been published - putting to draft therefore.
@tbsbdr fyi

Add release notes for ocis 5.0.7

---

modules/ROOT/pages/ocis_release_notes.adoc

Just two small fixes, locally tested, renders well.

Fix text in ocis release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

- Public and Private Links in the Sharing Panel
- Copy “Permanent Link” by default
- Public Link: Copy with or without password to clipboard
- Removed link types: “Can upload” and “Invited people”
- “Save as” in the app top bar
- Right Sidebar Transition
- Version Information In ~~Right~~ Left Sidebar
- Build your own Web Application: Web App Boilerplate

Added Release Notes 6.5.0

---

modules/ROOT/pages/ocis_release_notes.adoc

References: #75 (Added Release Notes 6.5.0)
Fixing text missed before merging the referenced PR.

Text fix for 6.5 release notes

---

modules/ROOT/pages/ios_release_notes.adoc

That entry was double present - removed

Remove double entry in iOS release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

- 4x Faster Image Previews
~~- 20 Newly Supported Image Formats like HEIC/HEIF or WebP~~ NOT yet implemented
- Only Office: 1-Click Document Templates
- Known Issues: OCM Federation: No Image Preview in Browser
@kulmann @micbar
Could you please also check correctness of content? I was not 100% sure about newly supported image file formats and supported template file formats 🙏 thanks

Added Release Notes 6.6.0

---

.asciidoctorconfig
.gitignore
antora.yml
modules/ROOT/pages/ocis_release_notes.adoc

Referencing:
https://github.com/owncloud/ocis/issues/10373 (Release 7.0.0)
https://github.com/owncloud/docs-ocis/pull/1029 (Migration and Update Guide for 5 to 7)
Adding ocis 7.0.0 release notes.

Create ocis 7.0.0 release notes

---

modules/ROOT/pages/server_releases.adoc

The appliance docs have been removed, we also need to remove the dead link to avoid build warnings.

Remove OC10 appliance reference

---

modules/ROOT/pages/server_releases.adoc

References: #87 (Remove OC10 appliance reference)
Commenting made the full build process run without warning, we now can finally remove the text block.

Finally remove already commented text block

---

modules/ROOT/pages/client_releases.adoc
modules/ROOT/partials/nav.adoc

Based on the request of @DeepDiver1975
This PR removes the branding docs from the navigation and client overview page. It must be merged BEFORE removing the branding docs from the build process.

Remove the Branding docs from the main page

---

modules/ROOT/pages/ios_release_notes.adoc

After adding the iOS 12.4 branch in docs, we need to add the release notes.

Add iOS 12.4.0 release notes

---

modules/ROOT/pages/desktop_release_notes.adoc

Adding the Desktop 5.3.2 release notes. This is a patch release only, no branching in `docs-client-desktop` encessary.

Add Desktop 5.3.2 release notes

---

modules/ROOT/pages/server_release_notes.adoc

Remove / adapt support and survey links as the targets are no longer valid.
There will be another PR in the `docs-server` repo doing the same. Other repos are not affected.
From the root of all doc repos:
* `find docs*/modules -type f -name *.adoc -exec grep -l 'support\@' {} \;`
* Global variables (attributes) do not contain any relevant attributes that would need removal.
* Branch relevant variables (attributes) do not contain any attributes that would need removal.
* Note that I also have made a quick look on the ownCloud homepage footer if I can identify relevant links but found none.
* Note that when I identified links in the docs that got redirected and/or are no longer in context of the link, I removed the link too.

Remove or adapt support and survey links

---

modules/ROOT/pages/ocis_release_notes.adoc

References: https://github.com/owncloud/docs-ocis/pull/1146 (Update ocis to 7.1.1)
This PR adds release notes for ocis 7.1.1

Release notes for ocis 7.1.1

---

modules/ROOT/pages/ocis_release_notes.adoc

Referencing: https://github.com/owncloud/docs/pull/5024 (Switch ocis to 7.1.2)
This PR updates the release notes for ocis 7.1.2

Update release notes for ocis 7.1.2

---

modules/ROOT/pages/ocis_release_notes.adoc

Adds a missing note because of changes in the compose examples.

Adding a missing note in the ocis release notes for 7.1.2

---

modules/ROOT/pages/android_release_notes.adoc

Adding Android 4.5.0 Release Notes, derived from the Android repo and Central.
Tested locally, renders fine.

Add Android 4.5.0 Release Notes

---

modules/ROOT/pages/ocis_release_notes.adoc

References: https://github.com/owncloud/docs/pull/5030 (Update ocis to 7.1.3)
Add release notes for ocis 7.1.3

Update ocis release notes for 7.1.3

---

modules/ROOT/pages/ocis_release_notes.adoc

This PR adds the release notes for ocis 7.2.0 (Addams)
Note that I tried my very best filtering out the important stuff from unreleased changelogs
Please add if something is missing.
The rest can be seen in the referenced changelog (when tagged)
Tested locally, renders fine.
Currently on daft to avoid accidentially merging before 7.2.0 is out.

Create ocis 7.2.0 release notes
