README.md

This link was no longer valid in README. I adjusted it to what I think it should be now.

fix: correct the link reference in README

---

docs/new-version-branch.md
modules/ROOT/pages/index.adoc
modules/ROOT/pages/ocis_release_notes.adoc
modules/ROOT/pages/server_release_notes.adoc
modules/ROOT/partials/nav.adoc
modules/notes_for_the_navigation_file_nav.txt

I did a review with the help of my IDE grammar checker.

fix: various grammar and typo issues

---

ext-antora/generate-index.js

ES index fix

---

modules/ROOT/pages/server_release_notes.adoc

These are the release notes for ownCloud Server 10.14.0.

Server 10.14.0 Release Notes

---

modules/ROOT/pages/ocis_release_notes.adoc

Harmonizing some stuff, using attributes for recurring links, adding links to patch releases etc.

Just some small fixes to the ocis release notes page

---

modules/ROOT/pages/ocis_release_notes.adoc

Else looks unprofessional when rendered. Was a leftover from updating.

Remove line break

---

modules/ROOT/pages/ocis_release_notes.adoc

Update the ocis release notes for 4.0.7

---

modules/ROOT/pages/index.adoc

add a link to Web UI config
todo: adoc syntax and backpots

Link to OCIS Web UI config

---

modules/ROOT/pages/ocis_release_notes.adoc

Add missing ocis 5.0.5 release notes.

Add ocis 5.0.5 release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

Done by adding `(Production)` or `(Rolling)` to the respective section name.
This now makes it easy in the TOC identifying a release and its state.
@tbsbdr fyi

Make production and rolling in ocis release notes distinctive

---

modules/ROOT/pages/ocis_release_notes.adoc

- Perma link
- App: External Site
- App: Custom Progress Bar
- Beautified Password Criteria

Release Notes 6.2.0 (Rolling)

---

modules/ROOT/pages/ocis_release_notes.adoc

Added Release Notes 6.3.0

---

modules/ROOT/pages/ocis_release_notes.adoc

Added URL to point to the rendered version of the release dates

updated release roadmap URL

---

modules/ROOT/pages/ocis_release_notes.adoc

- Moved latest production release note item (5.0.7) down to the other production releases Added:
-  Redesign of the Account Preferences
-  Enhanced Accessibility for the Datepicker UI
- Tiles View: Lazy Loading and Select All Checkbox
- Open Cloud Mesh - Bugfixes

Added Release Notes 6.4.0

---

modules/ROOT/pages/ios_release_notes.adoc

The iOS release notes needed an update

Update the iOS release notes

---

modules/ROOT/pages/android_release_notes.adoc

Add release notes for Android 4.4

---

modules/ROOT/pages/ocis_release_notes.adoc
site.yml

Add ocis 5.0.9 release notes

---

modules/ROOT/pages/ocis_release_notes.adoc

This PR adds a changelog for ocis 7.0.1 and 6.5.1

Add Changelog for ocis 7.0.1 and 6.5.1

---

modules/ROOT/pages/index.adoc
modules/ROOT/pages/ocis_release_notes.adoc

Fix / remove some orphaned xrefs.

Fix orphaned xrefs after removal of some deployment methods

---

modules/ROOT/pages/ocis_release_notes.adoc

References: https://github.com/owncloud/docs/pull/5007 (Enable ocis 7.1)
Add release notes for ocis 7.1
Language review welcomed

Add ocis 7.1 release notes

---

modules/ROOT/pages/server_release_notes.adoc

Add server release notes for `10.15.1` and `10.15.2`

Update server release notes

---

modules/ROOT/pages/ios_release_notes.adoc

iOS 12.6.0 has been released, this are the release notes

Add iOS 12.6 Release Notes

---

modules/ROOT/pages/desktop_release_notes.adoc

Add a new section with known issues because of filenames using special characters.

Add Desktop App Known Issues for v6.0.0
